### ISSUE TITLE
Restlet get with parameters

### ISSUE THREAD

**Issue by cgarrett69** [Petercw94/restsuite#2]
Hi.

How do you call a get restlet and pass in parameters

i.e. I would like to search if an order exists so need to pass in the order number

**Comment by Petercw94** [comment]
@cgarrett69 any url parameters can be specified in the url like any other parameters. If you are trying to pass parameters that are utilized in the actual RESTlet, you can adjust the restlet to a POST and send them in the body of the request. 

It would help if you could share a more specific example of what you are trying to do.

**Comment by crunchmasterdeluxe** [comment]
@cgarrett69 GET filter params mess up the signature generation, so it returns a 401 error. SuiteQL works though. Your query would look something like this: 

```
import restsuite
import os
# instantiate with your restsuite creds
netsuite_ql = restsuite.NetSuiteQL(
        account_id=os.getenv("NETSUITE_ACCOUNT_ID"),
        consumer_key=os.getenv("NETSUITE_CONSUMER_KEY"),
        consumer_secret=os.getenv("NETSUITE_CONSUMER_SECRET"),
        token_key=os.getenv("NETSUITE_TOKEN_KEY"),
        token_secret=os.getenv("NETSUITE_TOKEN_SECRET")
)
# query your netsuite
netsuite_response = netsuite_ql.suiteql(
     "Select * From order where api_name_order_number = 1234")
```

**Comment by Petercw94** [comment]
This is now fixed with Version 1 updates.
